### ISSUE TITLE
Disconnect All hidden bones?

### ISSUE THREAD

**Issue by xzhuah** [UuuNyaa/blender_mmd_tools#100]
The "Link to" logic in PMX and MMD is different.

For PMX model, when a bone A is "link to" another bone B, it only has visual effect: you will see a triangle link from A to B.
It won't affect the actual movement of bone A and B.

However in blender, when you link two Bones by connecting them, the connection will make sure these two bone are always phsically connected.

Usually it won't be a problem because for most bones, if they are linked, they are physically connected. But I recently see some models who is using a lot of hidden bones for controling expression. Some of the bones are connected, the expression is correct in MMD/PMXEditor, but not looking good in blender because some bones are not moving correctly because they are connected to other bones. This issue can be resolved by manually find these bones and press alt+p in edit mode and disconnect them.

Here is an example model:

https://drive.google.com/file/d/15U21mm5EIFvZTl_41A0jq44RO3TDRq1H/view?usp=sharing

The bone morph "でも、・・・" is not working correctly in Blender but looks good in PMXEditor

The reason is the hidden bone "mouth_S_1" is connected(linked) to the "mouth" bone. You can fix this by disconnect it in edit mode in Blender.
![N1WMJR$){7YSVE16{E{ATPV](https://github.com/UuuNyaa/blender_mmd_tools/assets/12613810/df9fc041-68cd-438a-9ad2-8c08226a0646)

![`9QG02CG{W XUCF@$1JN@HR_tmb](https://github.com/UuuNyaa/blender_mmd_tools/assets/12613810/bd1269e4-1de0-4689-bbc8-8cf92f6de76f).

I wonder if it make sense to not connecting any bones when importing PMX models, or at least not connecting for hidden bones？

**Comment by UuuNyaa** [comment]
Thank you for the report! 😀
I was surprised that such a critical bug remained in the old and supposedly well-tested code.

I fixed the bug with bc02663b2c868847291ed313da743b4863930c9b .

https://github.com/UuuNyaa/blender_mmd_tools/assets/70152495/b85e46a7-1b9b-4bc5-8ee7-c8f69f408a86

I will release a test version and would be happy to get your feedback.

**Comment by UuuNyaa** [comment]
Pre-release: https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v2.9.0

@xzhuah Please test it and give feedback.

**Comment by UuuNyaa** [comment]
@xzhuah v2.9.0 has a bug, so I have released **v2.9.1**. Please test with the new one.
https://github.com/UuuNyaa/blender_mmd_tools/releases

**Comment by xzhuah** [comment]
Thank you @UuuNyaa , I have tested with v2.9.1 and it works perfectly!

**Comment by rintrint** [comment]
Then why should we connect bones in Blender? Or should we disconnect all bones, whether they are hidden or not?

**Comment by UuuNyaa** [comment]
@rintrint I think that the bones are connected to ease editing and manipulation on Blender.

In general, Blender users connect bones when the parent and child bones move simultaneously and the coordinates of the parent tail and the child head match.
And, the various tools in Blender switch the process into cases depending on the connection state of the bones.
