### ISSUE TITLE
mmd tools fully crashes blender 3.6 randomly

### ISSUE THREAD

**Issue by ChegiCH** [UuuNyaa/blender_mmd_tools#105]
just to be sure I used it for a while on a clean 3.4 install and switched back to a clean 3.6 where it "immediatly" crashed after using it for a while. 
I'm not quite sure what's causing this but its certainly a big blocker to contiue using this addon in newer versions

**Comment by UuuNyaa** [comment]
Thanks for the report 😀
I think we need to wait for bug fixes for Blender itself to crash with the addon python code.

**Comment by ChegiCH** [comment]
I'm usually able to fix if I delete the whole blender folder and all configs

Problem starts to appear once you use rigidbodies too much of the mmd models

UuuNyaa ***@***.***> schrieb am Mi., 17. Apr. 2024, 13:02:
