### ISSUE TITLE
Character position stuck

### ISSUE THREAD

**Issue by TheRealJayjayli** [UuuNyaa/blender_mmd_tools#112]
Hello,

Apologies if this has been answered before. I occasionally have an issue where the character is stuck in position after I import motion files. I have this issue with many different models and motions.

The motion and models work fine on MMD.

![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/52780721/eb4702e3-34ab-4981-b1aa-773905826705)

Any help would be greatly appreciated. Thanks!

**Comment by UuuNyaa** [comment]
Probably you are importing FK leg motion.
Please turn off leg IKs.

**Comment by TheRealJayjayli** [comment]
This solved the issue, thank you so much!
