### ISSUE TITLE
MMD Tools Traceback Error

### ISSUE THREAD

**Issue by DigKingy** [UuuNyaa/blender_mmd_tools#113]
![Capture](https://github.com/UuuNyaa/blender_mmd_tools/assets/132033543/dd48d7de-b499-4152-9467-4f5871354de6)

**Comment by UuuNyaa** [comment]
Please try a clean install with all add-ons removed/disabled.
https://mmd-blender.fandom.com/wiki/MMD_Tools#Installation

**Comment by DigKingy** [comment]
Thanks! It now works just as expected!
![Capture](https://github.com/UuuNyaa/blender_mmd_tools/assets/132033543/9bd6fc9d-ccd6-4e6f-94be-7d004bda77c6)
