### ISSUE TITLE
Visibility show temps doesn't work for ncc files

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_tools#12]
This is a minor old bug, but I'm reporting it because I'm using the asset browser more often and it's bothering me a bit.

The ON/OFF of show temporary turns on/off mmd_bonetrack, but NCC files do not seem to be the target.

So, for example, if you turn off/on Exclude from viewport, or from the asset browser Append, and then Reset Visibility, the NCC coordinate axes will still be displayed at the feet of the character.

1 Imported PMX
![import and asemble all](https://user-images.githubusercontent.com/44924233/146902114-be0b11c6-1017-4118-aec6-dca81f659486.jpg)

2 Exclude from viewlayer OFF and ON
![disable and enable](https://user-images.githubusercontent.com/44924233/146902278-c9036b1e-7606-4310-94d0-63240b431ee5.jpg)

3 Visibility Reset ->  temporaly ncc is stil visible
![reset](https://user-images.githubusercontent.com/44924233/146902377-b1344f2f-08c2-47ab-aa41-9c698b31454b.jpg)

**Comment by nagadomi** [comment]
You can change the visibility of all ncc objects at once by holding down the SHIFT key and clicking the `temporary`'s visibility icon.

---

I guess this behavior is by design from 2.7x. ncc is only meant for constraints and no need to change the visibility, so it is not targeted by the toggle button that changes the visibility.

**Comment by listelin** [comment]
> You can change the visibility of all ncc objects at once by holding down the SHIFT key and clicking the `temporary`'s visibility icon.

Thank you!
I know that, and I do, but I think it's useful to be able to do justice to the visibility feature.

> I guess this behavior is by design from 2.7x. ncc is only meant for constraints and no need to change the visibility, so it is not targeted by the toggle button that changes the visibility.

I understand. Maybe you're right.
But as I mentioned above, this can be a problem if you show/emerge characters per collection, or if you Append them in the asset browser.

It's not really a big problem, but it's something I'd like to see improved if possible.

**Comment by UuuNyaa** [comment]
> I guess this behavior is by design from 2.7x. ncc is only meant for constraints and no need to change the visibility, so it is not targeted by the toggle button that changes the visibility.

Can the latest rigid body physics eliminate the use of ncc?
I think the ncc method needs to be fixed because it causes strange collisions.

> It's not really a big problem, but it's something I'd like to see improved if possible.

I think adding and linking collections is an important feature.
So I will add the ability to hide the ncc objects to the reset button.

**Comment by nagadomi** [comment]
>Can the latest rigid body physics eliminate the use of ncc objects?
>I think the ncc method needs to be fixed because it causes strange collisions.

I am not sure if there is a better method than ncc method.
The following is some background knowledge of ncc as far as I know.

Blender and MMD have different rules for defining rigid body collision.
- Blender: Define collision group (Only objects in the same group will collide)
- MMD: Define non-collision group (Only objects in the same group will not collide)

mmd_tools simulates MMD non-collision group in the following way.

1. Make all rigid bodies in the same group (they will all collide with each other).
2. Disable collisions between rigid bodies that do not collide as defined by Collision Group Mask setting using RigidBodyConstraint (ncc).

**Comment by UuuNyaa** [comment]
Thank you for the information.
I could understand the background.

**Comment by listelin** [comment]
I confirm fixed. thank you
