### ISSUE TITLE
Textures missing when exported to GLB

### ISSUE THREAD

**Issue by atsuya** [UuuNyaa/blender_mmd_tools#124]
Hi,

Thank you so much for the awesome tool! I really enjoy playing with it :)

I'm trying to export the imported MMD model to GLB format, but it seems like it's missing the textures. The imported MMD model [looks great](https://github.com/UuuNyaa/blender_mmd_tools/assets/64097/5f5c497b-30a0-405a-8888-fe5930108ed1) on Blender, but the [textures are missing](https://github.com/UuuNyaa/blender_mmd_tools/assets/64097/c36915e3-67a4-4e30-82e3-6a99f4e0a18c) (or at least not showing) when exported to GLB format.

I found this [bug](https://github.com/powroupi/blender_mmd_tools/issues/330) and wanted to try the proposed solution, but I can't find "Convert Materials for Cycles" nor "Convert to Principled BSDF" options in the current mmd_tools.

Is there anything I should be doing when exporting the imported MMD model to GLB format?

Thank you!

**Comment by UuuNyaa** [comment]
> I can't find "Convert Materials for Cycles" nor "Convert to Principled BSDF" options in the current mmd_tools.

You may find the following URL helpful:
https://mmd-blender.fandom.com/wiki/MMD_Tools/Release_Notes#UI_improvements_and_changes

> but the textures are missing (or at least not showing) when exported to GLB format.

The PMX models do not contain texture images and treat them as separate files, so the GLB format may not properly resolve links to images.

**Comment by atsuya** [comment]
Thank you for the reply. I used "Convert to Blender" with "Convert to Principled BSDF" enabled, and it [partially worked](https://github.com/UuuNyaa/blender_mmd_tools/assets/64097/bd17eb78-fc25-4306-9549-2e97431a1cca) (still exported as GLB).

> The PMX models do not contain texture images and treat them as separate files, so the GLB format may not properly resolve links to images.
If that is due to this reason, do you have recommendation on which format I should try?

**Comment by UuuNyaa** [comment]
> If that is due to this reason, do you have recommendation on which format I should try?

Sorry, I'm not familiar with export formats, so I don't know.
According to your upload image, the textures export seems to be successful. What problems remain?

**Comment by atsuya** [comment]
There are some parts of textures that don't look right (e.g. light blue-ish parts on the legs), so I thought the "Convert to Blender" feature only partially worked. It could be an issue on the client that uses the exported GLB model.

Nonetheless, thank you for your support and I'll close this one as I think I got what I wanted to know from you. Thank you again for the wonderful tool!
