### ISSUE TITLE
Traceback error when exporting model

### ISSUE THREAD

**Issue by hasukidawg** [UuuNyaa/blender_mmd_tools#125]
so, i was able to export models before i fromatted my pc, but now after installing the script again it gives me a "traceback" error, and doesn't export anything. i attached the meshes to the master bone created using the tool but no matter what i do i can't export anything, am i doing something wrong? i'm using the newest script release with Blender 3.6

here's the log containing the error:

![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/153738309/e3a00e0b-46d1-4797-8da6-2e7a7f7ff115)

**Comment by UuuNyaa** [comment]
This problem occurs if the model does not have an armature object or a rigid body group object.
Does the model have these objects as children of the model root object?

**Comment by hasukidawg** [comment]
> This problem occurs if the model does not have an armature object or a rigid body group object. Does the model have these objects as children of the model root object?

yes, i tried to export a ripped model just now and the same error pops up. i was able to export models successfully not so long ago by just selecting the armature, using the "convert model" option in the MMD tab and then exporting it.

![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/153738309/4656058c-e0e6-4efb-998c-28344acd9ec8)
^ i successfully exported this model to MMD with converted armature and everything some weeks ago but now the same model won't export after reinstalling the tool

**Comment by UuuNyaa** [comment]
The previous release has this issue, so we have made a fixed release [v2.10.2](https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v2.10.2).
Please test it if you have the time.

**Comment by hasukidawg** [comment]
> The previous release has this issue, so we have made a fixed release [v2.10.2](https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v2.10.2). Please test it if you have the time.

![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/153738309/ac1b3edc-dd6a-4ede-947f-830d556abe5d)
worked! thank you for taking your time to troubleshoot this problem :)

**Comment by UuuNyaa** [comment]
Thank you for testing.
