### ISSUE TITLE
ValueError: bpy.app.translations.register: translations message cache already contains some data for addon 'mmd_tools'

### ISSUE THREAD

**Issue by supahfox** [UuuNyaa/blender_mmd_tools#127]
Trying to install mmd tools from branch [blender-v4](https://github.com/UuuNyaa/blender_mmd_tools/tree/blender-v4), it returns this

![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/31490939/205dcb94-d9b5-4e3b-b233-d55ed1404d26)

**Comment by Yusarina** [comment]
Personally I would not be using MMD tools on Blender 4.0, as the developer as stated in other issues, there don't plan on releasing it unto the LTS for 4.2 comes out.

see [this](https://github.com/UuuNyaa/blender_mmd_tools/issues/116#issuecomment-1883508330) for more info.

There for this means the blender-v4 branch is not stable and may not be unto later this year.

**Comment by UuuNyaa** [comment]
Please try [MMD Tools v4.x](https://github.com/UuuNyaa/blender_mmd_tools/releases) and give us feedback.

**Comment by mienaiKnife** [comment]
I got a similar error message while trying to update my version of MMD Tools to 2.10.3 in Blender 3.6 and I'd like to know how to fix this.

**Comment by mienaiKnife** [comment]
Nevermind, disabling the CATS plugin before enabling MMD Tools seems to have fixed my problem
