### ISSUE TITLE
Some rigid's radius will be zero when the pmx model importing.

### ISSUE THREAD

**Issue by meiyoufeng116** [UuuNyaa/blender_mmd_tools#13]
When I was importing the PMX model into blender, some rigid's radius will be 0, and it will cause some physics error. 

![image](https://user-images.githubusercontent.com/37991414/147388308-5f4e71e3-adc4-441b-b0a5-a4a793bf17ad.png)

Some rigids related to breast and head rigids show this kind of error.

the blender version is 3.0 
the Plug-in version is 1.1.12（shows in __init__.py）

**Comment by listelin** [comment]
1.1.12 may be mmd_uuunyaa_tools version.

mmd_tools latest version (1.10 ) fixed this problem.  Please check mmd_tools version.
see: https://github.com/UuuNyaa/blender_mmd_tools/issues/6

![riameter](https://user-images.githubusercontent.com/44924233/147388739-ae6dbb34-109d-49b7-a012-8abf4b68a153.jpg)
