### ISSUE TITLE
Why does it output without animation when exporting to FBX

### ISSUE THREAD

**Issue by snowsun137** [UuuNyaa/blender_mmd_tools#165]
- Blender: 3.3
 - mmd_tools: v 2.10.3
 - OS: windows11

Hello
I'm going to create an animation in Blander and then export it to FBX and use it in another tool (Cinema4d).
However, if you import it to another tool, the animation is missing (only the pose of the current frame is printed on the blender)
Is there anything I didn't know well about this?

Thank you for creating a comfortable tool.

**Comment by rintrint** [comment]
This is not an issue related to this plugin. It's actually a Blender-related problem. You can check the FBX export options.
https://docs.blender.org/manual/en/4.2/addons/import_export/scene_fbx.html#fbx
Please check the official documentation or search online for tutorials on how to export FBX from Blender.

Also make sure that "Bake Animation" is checked.
<img width="223" alt="Snipaste_2024-07-17_14-53-29" src="https://github.com/user-attachments/assets/7b093e99-5f08-482c-a477-73a7917f5e8f">

I didn't try Blender 3.3, but I haven't encountered any problems in 3.6 and 4.2 when exporting fbx with animation.
