### ISSUE TITLE
When I apply physics to hair and chest parts, it falls to the floor.

### ISSUE THREAD

**Issue by snowsun137** [UuuNyaa/blender_mmd_tools#166]
## What version of softwares are you using?
 - Blender: 3.3v
 - mmd_tools: v 2.10.3
 - OS: windows11

When I apply physics to my model's hair and chest parts, it falls to the floor.
It applies well to the rest of the collar.
I'm not using blender as the main tool
Please understand that you have a low understanding of the tool

Attached is the file I was working on.
If there's anything that's lacking, please let me know
If it doesn't fit the bulletin board, I'll delete it.
Thank you.
[Koleda_setup.zip](https://github.com/user-attachments/files/16277955/Koleda_setup.zip)

![image](https://github.com/user-attachments/assets/db69c015-4bec-455c-9511-11de778d4b94)

![image](https://github.com/user-attachments/assets/877e706d-4a70-4c47-bd48-178a19c82537)

**Comment by rintrint** [comment]
You can download the same model here. This one works fine.
It seems like you broke the model.
https://www.aplaybox.com/details/model/eZ8euOGyYXbi

**Comment by snowsun137** [comment]
Thank you soooo much :)
