### ISSUE TITLE
AssertionError when trying to export VMD data

### ISSUE THREAD

**Issue by aSquidfox** [UuuNyaa/blender_mmd_tools#17]
So yeah, been trying to export a VMD animation and I've been coming up with this error. For context the animation is a few NLA strips baked into a single Action. Pose exporting works fine but VMD exporting doesn't.
![image](https://user-images.githubusercontent.com/97125115/148111854-14214f0d-2595-45d0-a73b-602d755817be.png)

**Comment by UuuNyaa** [comment]
Can you share the .blend file with me to reproduce the problem?

**Comment by aSquidfox** [comment]
Yeah sure, how should I go about doing that? Can't upload a .blend on here.

**Comment by aSquidfox** [comment]
I'm actually stupid, forgot I could just upload on MEGA and share the link.
Here you go bud, https://mega.nz/file/R81g1AaI#Q630hUSWkwtUWOHYCRD7QZaSb9toUqbyz3Ha2v1SEvE

**Comment by nagadomi** [comment]
This error occurs when multiple bones have the same MMD bone name (name_j).

**Comment by aSquidfox** [comment]
I thought so too but in order to test it I imported a motion and then immediately exported it and the export worked fine, would the error occur only when a duplicate bone has a keyframe on it?

**Comment by nagadomi** [comment]
When you import a motion, each bone with the same MMD name will have the same keyframe.
When you create a motion in Blender, each bone with the same MMD name will have a different keyframe, which makes it inconsistent.
Also, the VMD exporter records keyframes using the MMD bone name, not the Blender bone name, so if the MMD bone name is not correct, the exported motion will not be the same as in Blender.

**Comment by UuuNyaa** [comment]
As @nagadomi said, the names of 左腕 and 左手首 were in conflict.
I resolved the conflicts and was able to export without any problem.

https://user-images.githubusercontent.com/70152495/148386922-b2a94474-9810-4f47-9e01-241a81a59e10.mp4

**Comment by aSquidfox** [comment]
I see, I'll make sure to do a thorough check on the models from now on, thanks a lot guys.
