### ISSUE TITLE
Is there any way to convert the FOV imported by mmd from integer to float

### ISSUE THREAD

**Issue by abukumaL1** [UuuNyaa/blender_mmd_tools#173]
## What version of softwares are you using?
 - Blender: 3.6.9
 - mmd_tools: v2.10.2
 - OS: Windows 10
 
Because the fov of mmd is always an integer by default, some game-extracted camera data with floati values cannot be used in mmd
but mmd has a mod that can make fov display as float number.Is there any way to use mmdtools?

**Comment by fmnijk** [comment]
Sorry but I don't get your point. Blender's focal length is already a floating-point number.

**Comment by nagadomi** [comment]
See https://github.com/powroupi/blender_mmd_tools/issues/287
