### ISSUE TITLE
Is there an API document to use this addon by python?

### ISSUE THREAD

**Issue by butaixianran** [UuuNyaa/blender_mmd_tools#18]
I'd like to use it by python, in my own addon, for example to import model and vmd motion by script.

Is there an API document for that?

thanks

**Comment by UuuNyaa** [comment]
There is no API manual.
However, you can read the code and understand the API.
https://github.com/UuuNyaa/blender_mmd_tools/blob/main/mmd_tools/core/model.py

I am using the following code to load and use mmd_tools modules.

```python
def is_mmd_tools_installed() -> bool:
    return importlib.find_loader('mmd_tools')  # pylint: disable=deprecated-method

def import_mmd_tools():
    return importlib.import_module('mmd_tools')

mmd_root_object = import_mmd_tools().core.model.Model.findRoot(blender_object)
mmd_model = import_mmd_tools().core.model.Model(mmd_root_object)
```

**Comment by butaixianran** [comment]
Hi, thanks for reply, I end up right my own function to import vmd file.

Anyway, this new blender addon could be useful for anyone like mmd and blender.

Check it out if you like:
https://github.com/butaixianran/Blender-Vmd-Retargeting
