### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by lil-cristal** [UuuNyaa/blender_mmd_tools#21]
Does not work with blender 3.0 +

**Comment by listelin** [comment]
Which functions are not working with blender 3.0+?
And what exactly is the situation when it doesn't work?

**Comment by FlashlightET** [comment]
can't import PMX
![image](https://user-images.githubusercontent.com/29938499/154812521-d952bffa-2cef-455a-b794-ba047c2b70d8.png)

**Comment by UuuNyaa** [comment]
@FlashlightET 
Maybe you are using a old version.
Please install the latest version.
see: https://mmd-blender.fandom.com/wiki/MMD_Tools
