### ISSUE TITLE
How do I work with AutoLuminous?

### ISSUE THREAD

**Issue by ChandelureF-5** [UuuNyaa/blender_mmd_tools#28]
I don't see an option for this "AutoLuminous" thing.

**Comment by UuuNyaa** [comment]
I implemented the equivalent in MMD UuuNyaa Tools v1.2.9

https://user-images.githubusercontent.com/70152495/161531083-35900c10-45dd-40e3-be3b-42698d95305c.mp4

https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/releases
