### ISSUE TITLE
Animating Material Morphs

### ISSUE THREAD

**Issue by SeleDreams** [UuuNyaa/blender_mmd_tools#32]
Hi, I want to animate an MMD model that relies on material morphs to change aspects of its clothing.
So I'd need to be able to place keyframes that affect the materials during the animation, is there any way to achieve this result ?
If yes, how would I achieve it ?
Thanks in advance

**Comment by One-sixth** [comment]
Hi, you can find a solution on the wiki.
https://mmd-blender.fandom.com/wiki/MMD_Tools/Manual#Morph_.28Material.2C_UV.2C_Bone_and_Group_Morphs.29

**Comment by SeleDreams** [comment]
> Hi, you can find a solution on the wiki. https://mmd-blender.fandom.com/wiki/MMD_Tools/Manual#Morph_.28Material.2C_UV.2C_Bone_and_Group_Morphs.29

whenever I try to set keyframes for these key shapes i get crashes EXCEPTION_ACCESS_VIOLATION

**Comment by listelin** [comment]
Note: blender 3.1.x bug detail

## Crash Driver setting in 3.1 ( safe in 3.0)  (This driver setting is used by mmd_tools material morph)
SingleProperty
Prop = object
Path=data.shape_keys.key_blocks["Key 1"].value

-> space key to play causes crash

## Safe Driver setting in 3.1
SingleProperty
Prop = Key
Path=key_blocks["Key 1"].value

[driver=key-safe.zip](https://github.com/UuuNyaa/blender_mmd_tools/files/8530040/driver.key-safe.zip)
[driver=object-crash.zip](https://github.com/UuuNyaa/blender_mmd_tools/files/8530041/driver.object-crash.zip)

**Comment by listelin** [comment]
This blender bug has been fixed in the May 17 version of 3.2beta and 3.3Alpha.

It should be fixed in 3.1.3 as well, but the timing is not yet determined.
