### ISSUE TITLE
Create empty vertex group if the vertex group corresponding to the bone name does not exist.

### ISSUE THREAD

**Issue by One-sixth** [UuuNyaa/blender_mmd_tools#33]
Hello.
The bone order is dependent on the order of the vertex groups of the same name.
Sometimes vertex groups with the same name are deleted by mistake, resulting in incorrect bone order when the PMX model is exported.
We can add a button. An empty vertex group is created automatically if the vertex group for the bone name does not exist.
And then, sort the vertex group by BONE_HIERARCHY.

Here is my implemente. Adding this feature would be easy.
```python

import bpy

obj = bpy.context.active_object

arm = obj.find_armature()
assert arm is not None
bone_names = set(arm.pose.bones.keys())

vgs = obj.vertex_groups
vg_names = set(vgs.keys())

lack_vg_names = bone_names - vg_names
lack_vg_names = [n for n in lack_vg_names if not n.startswith('_')]

for n in lack_vg_names:
    vgs.new(name=n)

bpy.ops.object.vertex_group_sort(sort_type='BONE_HIERARCHY')
```

**Comment by UuuNyaa** [comment]
Thank you for your suggestion 😃
I will consider UI.
Do you think adding a ![image](https://user-images.githubusercontent.com/70152495/165897451-c0f1a811-ce55-4848-8828-a1a7b78bc35b.png) button to right bottom of **Bone Order** panel would be easier to use?
![image](https://user-images.githubusercontent.com/70152495/165897366-b573e93f-ace9-48ba-ad6c-2bbcb2becb8d.png)

**Comment by One-sixth** [comment]
I think it's ok.
Perhaps a red warning could be added to remind the user to use this feature when the requested vertex group does not exist.

**Comment by UuuNyaa** [comment]
f96ab576151716ef98bbd35d537ebb9b6bc20ca1
![image](https://user-images.githubusercontent.com/70152495/175325917-c268d6ca-fbc2-48c4-9f56-497dca9bda54.png)

**Comment by One-sixth** [comment]
Great!
