### ISSUE TITLE
Support for PMX 2.1 or How to import vertex colors.

### ISSUE THREAD

**Issue by MediaMoots** [UuuNyaa/blender_mmd_tools#35]
Hi there!

I was wondering if it would be possible to support PMX version 2.1

That version has support for Vertex Colors, and I would like to use that, would it be possible to support this version?
https://gist.github.com/felixjones/f8a06bd48f9da9a4539f
![image](https://user-images.githubusercontent.com/81146974/164967312-d15323bd-276c-438a-a7cc-bb38153461a1.png)

Thanks!

**Comment by listelin** [comment]
I think this feature is not a priority for blender_mmd_tool, since pmx2.1 is not usable in MMD and if you use pmx models in blender, you can freely increase the UVs and use vertex colors.

I have not seen any pmx 2.1 models that I would like to import into blender either.

Just my opinion.

**Comment by MediaMoots** [comment]
Well, i have a plugin that can export anime models from a unity game and those models use Vertex Colors for shader calculations, if MMD-Tools can at least import those vertex colors then it would be enough.

**Comment by MediaMoots** [comment]
@UuuNyaa 
Cool that issue is quite helpful, so would it be possible to automatically use the last or first additional UV and set it as vertex colors?
Maybe with an option in the import dialog?

**Comment by UuuNyaa** [comment]
> so would it be possible to automatically use the last or first additional UV and set it as vertex colors?

No, MMD Tools has no such feature.
Geometry Nodes may be able to set vertex colors.

- [Blender 3.0: Transfer UV map from shader to geometry nodes?](https://blender.stackexchange.com/questions/249174/blender-3-0-transfer-uv-map-from-shader-to-geometry-nodes)
- [Geometry Nodes output to vertex color](https://blender.stackexchange.com/questions/245691/geometry-nodes-output-to-vertex-color)

**Comment by UuuNyaa** [comment]
@MediaMoots 
By the way, how promising do you think PMX 2.1 is?
I think we should use [VRM format](https://vrm.dev/en/) if we need such a data format.

**Comment by MediaMoots** [comment]
> No, MMD Tools has no such feature.

Ok, I guess I can write a script to do that in python.

> Geometry Nodes may be able to set vertex colors.

That may work in blender, but my workflow is to import PMX to blender then export as FBX for an external game engine.

> By the way, how promising do you think PMX 2.1 is?

The only reason I thought I needed PMX 2.1 is for vertex colors, but if there's a way to add vertex colors to the mesh on version 2.0 then I won't need 2.1

**Comment by UuuNyaa** [comment]
> >   Geometry Nodes may be able to set vertex colors.
>
> That may work in blender, but my workflow is to import PMX to blender, clean it up, make textures, then export as FBX for an external game engine.

Do you already have a PMX file with vertex colors inside?

What do you think of the following steps?
1. convert vertex colors (vec3?) in PMX to UV (vec4) on PMXEditor?
2. import PMX to Blender
3. convert UV (vec4) to vertex colors by Geometry Nodes
4. clean it up, make textures
5. export as FBX for an external game engine

**Comment by MediaMoots** [comment]
Ok thank you, I'll try that out, I have another question, does the PMX format support tangents? Thanks.

**Comment by MediaMoots** [comment]
Hi, that works well, thanks!

After looking into the vrm format it seems quite promising, does it support separate meshes? As pmx only supports one single mesh.

**Comment by UuuNyaa** [comment]
> After looking into the vrm format it seems quite promising, does it support separate meshes?

Probably yes. 
VRM specs: https://github.com/vrm-c/vrm-specification/tree/master/specification/0.0#gltf-20-mesh
glTF-2.0 specs: https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes

**Comment by MediaMoots** [comment]
Ok cool, thanks for all the help!
