### ISSUE TITLE
Certain imported PMX model appears a glitchy black in solid view mode 

### ISSUE THREAD

**Issue by EltoCode** [UuuNyaa/blender_mmd_tools#37]
When certain pmx models are imported, they do not render correctly in solid view mode. They render with this glitchy black material, best described with the GIF below. So far I've been unable to discern what causes this unintended behavior in certain models. This glitch occurs in Blender 2.9 and 3.1

![import_glitch](https://user-images.githubusercontent.com/45271085/167466458-1030f2ab-06b8-41df-bf8c-229c5d1f4fdb.gif)

I've attached a zip file containing 2 models. One causes the glitch, the other does not. They are named as such

[import_glitch.zip](https://github.com/UuuNyaa/blender_mmd_tools/files/8654047/import_glitch.zip)

**Comment by UuuNyaa** [comment]
Thanks for the report 😃
However, I could not reproduce the problem in my environment (Blender 3.1.2 and 2.93.9)

https://user-images.githubusercontent.com/70152495/167548081-5912682b-e65e-4e28-9470-da86ffb7d7dc.mp4


Can you explain in detail how to reproduce it?

**Comment by nagadomi** [comment]
Maybe AMD driver issue. https://github.com/powroupi/blender_mmd_tools/issues/317

**Comment by EltoCode** [comment]
> Maybe AMD driver issue. [powroupi#317](https://github.com/powroupi/blender_mmd_tools/issues/317)

I just tested it on a Nvidia GPU and the glitch does not occur. So it's true that the issue only occurs on AMD machines.

> Can you explain in detail how to reproduce it?

Importing a glitch model with the plugin will cause the glitch.
This is what causes the glitch on affected models. If the model contains any materials with the "Opaque" field set to a value that is not 1. Then the glitch occurs on that model. So it's a transparency issue with the AMD driver

![image](https://user-images.githubusercontent.com/45271085/167668858-1851d549-6640-4522-bac1-3e9620e9b133.png)

**Comment by UuuNyaa** [comment]
> it's a transparency issue with the AMD driver

Thanks for the information 😃
I will not change MMD Tools as it seems to be an AMD driver issue.
Please let me know if you find a workaround.
