### ISSUE TITLE
Can add a copy texture option?

### ISSUE THREAD

**Issue by Kasim3157** [UuuNyaa/blender_mmd_tools#38]
First of all, Thank you for maintain mmd tools!

In some case import other format model it use different shader. It has its own texture file name or file path.
After convert and export to pmx format. Is just a white model whithout any texture in MMD.
So can add a option for copy different shader's texture file path to MMD shader texture file path?

For example this is "[yk_gmd_io](https://github.com/theturboturnip/yk_gmd_io)"
For convert to pmx with correct texture, copy texture_diffuse file name and past to MMD texture.
It will change to MMD shader and save the texture file path.
![exp2](https://user-images.githubusercontent.com/105275585/167587467-4c06cc5e-781d-4a5b-82dc-54beb9f2f3b3.JPG)
![exp3](https://user-images.githubusercontent.com/105275585/167589807-f9535ed8-7b5f-4a22-98cd-f6dc162fba96.JPG)

**Comment by UuuNyaa** [comment]
Thanks for the request 😃

3D Viewport > Sidebar > MMD > Model Production > Convert Model to convert materials for MMD, but this feature is not enough?
![image](https://user-images.githubusercontent.com/70152495/168440594-6186180a-30f5-40fb-ab8b-6f59273a860b.png)

Also, what do you think about the difficulty in deciding which node to adopt for the Mmd Base Tex when there are multiple Image Texture nodes in the original shader?
