### ISSUE TITLE
After Importing the model , the body of the model was deformed in different degrees

### ISSUE THREAD

**Issue by NyakoCombo** [UuuNyaa/blender_mmd_tools#39]
![image](https://user-images.githubusercontent.com/60848100/168005048-ef9ea537-6ed9-408c-8b8b-240467091abe.png)
![image](https://user-images.githubusercontent.com/60848100/168005105-e4b7d185-2de5-4c17-bf85-b488bd461a2c.png)
 
 Blender3.1.2
 mmdtools 2.2.5

**Comment by nagadomi** [comment]
See https://github.com/powroupi/blender_mmd_tools/issues/153

**Comment by NyakoCombo** [comment]
Yes，Thank you so very much ，Is not completely , Sour type ,
But it's enough to be useful

**Comment by NyakoCombo** [comment]
After MMD IK Loop Factor
 
 
![image](https://user-images.githubusercontent.com/60848100/168017256-3e942538-dc11-486e-ac95-a8576cb3c49f.png)
![image](https://user-images.githubusercontent.com/60848100/168017325-56c2989d-85e1-41d8-a304-795beaeb8417.png)

**Comment by nagadomi** [comment]
Maybe SDEF weight is used for arm twist bone. Try `MMD Tab > Model Setup > Assembly > SDEF(Bind)`.
If this does not solve the problem, there may be a problem with the structure of the arm twist bone that is not compatible with blender.

**Comment by NyakoCombo** [comment]
Yes，Thank you ！！
