### ISSUE TITLE
[Noob Problem] Most parts of imported model are pixelated and transparent

### ISSUE THREAD

**Issue by Sukochi** [UuuNyaa/blender_mmd_tools#42]
![image](https://user-images.githubusercontent.com/41372950/169631615-0195cf95-d6ea-4832-b6c0-a964961c919f.png)
Material Shading (Layout Tab)
- some parts are kinda pixelated and transparent
- turned off Toon Texture and Sphere Texture but still look weird
- tried importing a different character model but was fine (is it just a model problem?)

![image](https://user-images.githubusercontent.com/41372950/169631662-2e8a6567-2209-414b-9706-357be98249e8.png)
Solid Viewport (Texture Paint Tab)
- it seems fine here though

I'm new to Blender so I don't really know how to fix this. Couldn't find any problems similar when I tried looking it up online so any help/suggestions are welcomed. Thank you!

**Comment by UuuNyaa** [comment]
Perhaps the alpha values of the model materials are wrong 🤔

Try adjusting Properties > Material Properties > MMD Material > Diffuse Color: Alpha
![image](https://user-images.githubusercontent.com/70152495/172120555-2755e3eb-baf4-4468-8168-33e703f35a8e.png)
