### ISSUE TITLE
[Physical Bone Bug] Using use_connect causes translation transforms to be ignored.

### ISSUE THREAD

**Issue by One-sixth** [UuuNyaa/blender_mmd_tools#50]
Hello. After modifying a model, I found that the model's skirt works fine in MMD, but is often pierced in Blender.
Then I found this bug.
Physics bones need to accept translations and rotations from rigid bodies. But when the physics bone enable "use_connect", the rigid body translation is ignored.
This resulted in physical bones not accurately following rigid bodies.

However, setting use_connect directly will cause the child-bone to be lost. When building physics, we may need to find a place to store the child-bone. Avoid lost child-bone when exporting pmx model..

Default
![default](https://user-images.githubusercontent.com/23693633/174068347-768560f2-02d2-40a5-a3b8-ad2790f835c4.png)
Disable use_connect
![disconnect](https://user-images.githubusercontent.com/23693633/174068645-8e9401be-70d3-442f-afc2-a4e7b028f58a.png)

pmxedit
![pmx](https://user-images.githubusercontent.com/23693633/174070127-761c0bd3-c37d-412a-88d6-887717eefcea.png)

no lost child-bone
![no-lost](https://user-images.githubusercontent.com/23693633/174071711-80669e76-9f15-433b-9550-3762701479a6.png)

lost child-bone
![lost_child_bone](https://user-images.githubusercontent.com/23693633/174071509-3b4e7fd8-2ea9-415f-b869-4514f0461c62.png)

Here is the code to simply turn “use_connect” off and you can quickly experiment with other models.
```python
import bpy

arm = bpy.data.armatures["pose"]

for b in arm.edit_bones:
    b.use_connect = False

print('Success')

```

This is the model I use for bug checking.
[bug_check.zip](https://github.com/UuuNyaa/blender_mmd_tools/files/8918650/bug_check.zip)

**Comment by UuuNyaa** [comment]
Thank you for your report 😃

I have the following method in mind to solve the problem.

On build physics:
1. save bone connection data to bone's custom properties
2. disconnect bone connections
3. build physics

On demolish physics:
1. demolish physics
2. re-connect bone connections by bone's custom property
3. remove bone's custom properties

However, the method does not allow exporting models in built state.
What do you think about the method?

**Comment by UuuNyaa** [comment]
@One-sixth Thank you for your opinion.
Allows export even if models in built state 😃
f8ad7e00faa7590082051a742ac7a5b71451e29b

**Comment by One-sixth** [comment]
Great! Thanks for your hard work.

**Comment by UuuNyaa** [comment]
Bone "use_connect"s are turned off, causing problems with rigid bodies flying off with quick movements.
![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/70152495/0f944036-ea7e-440a-951d-1941616c8f78)

**Comment by UuuNyaa** [comment]
To solve the issue, set Rigid Body Physics Substeps=6, Iterations=10.
![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/70152495/323150bd-19e0-46c5-8bff-1cf065586e12)

![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/70152495/4af21195-3f2b-4e65-ab67-45ad28202281)

**Comment by One-sixth** [comment]
I also encountered the same problem before. After a previous Blender version update (possibly Blender 3.3), the solution is the same as yours.

I guess there have been some changes in the rigid body constraint algorithm.
