### ISSUE TITLE
Logging level = DEBUG affects logs of other add-ons

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_tools#51]
これはバグとは言えませんが、同じ事象に直面している人もいるかと思い共有します。

1. mmd_toolsはログレベルをDEBUGに設定してログを出力している
https://github.com/UuuNyaa/blender_mmd_tools/blob/22fba405e07318c375a6d9a2fff640420c62a6ca/mmd_tools/__init__.py#L20

2. このログレベル設定は他のアドオンにも影響を与える

3. 例えば、blenderkitの最新版はDEBUGレベルで大量のログを出力するようになっているため、
　mmd_toolsとblenderkitを両方有効にするとコンソールログがblenderkitのログで埋まってしまう

blenderkit側も他のアドオンのロギングレベルと独立させるよう検討するとのことですが、当面mmd_toolsとblenderkitを併用する場合、上記のmmd_toolsのlogging.DEBUG設定をコメントアウトしたほうが良いかもしれません。

---
This is not a bug, but I share it with you in case some of you are facing the same issue.

1. mmd_tools is outputting logs with log level set to DEBUG
https://github.com/UuuNyaa/blender_mmd_tools/blob/22fba405e07318c375a6d9a2fff640420c62a6ca/mmd_tools/__init__.py#L20

2. This logging level setting also affects other add-ons.

3. For example, the latest version of blenderkit outputs a large amount of logging at the DEBUG level, so if both mmd_tools and blenderkit are enabled, the console log will be filled with blenderkit's logs.

The blenderkit side will consider making the logging level independent of other add-ons, but for the time being, if you use mmd_tools and blenderkit together, you may want to comment out the above logging.DEBUG setting in mmd_tools.

**Comment by UuuNyaa** [comment]
提案ありがとうございます 😃
他のアドオンのロガーと干渉しないようにこのコードを削除しようと思います。
根本的な解決のためにはロガー取得コードを `logging.getLogger("mmd_tools")` に置き換える必要があるかもしれません。

Thanks for the suggestion 😃
I will remove this code to avoid interfering with other add-on loggers.
A radical solution may require replacing logger getting code with `logging.getLogger("mmd_tools")` .
