### ISSUE TITLE
Is it possible to translate English armature to Japanese?

### ISSUE THREAD

**Issue by LuluViBritannia012** [UuuNyaa/blender_mmd_tools#55]
Hey there,
So, I discovered this tool a few years ago, and although it is great when working with MMD, I had one big issue: most of MMD models and motions are named in Japanese, but mmd_tools only gives us an armature in English. That means we can convert any model in pmx but can't use those models with most MMD motions since those are for Japanese models.
So, is it possible to translate English bones to Japanese now? There's just too many bones for me to accept doing that manually. I also don't want to just get rid of the armature and rig everything back on a new compatible one.

I guess I could just disable the translation, but I'm pretty sure all my models have Japanese bones by default, so it wouldn't help xD!

If it's not possible, do you have any advice?
Thank you for this tool!

**Comment by UuuNyaa** [comment]
Please try **Global Translation** feature. 
![image](https://user-images.githubusercontent.com/70152495/178097640-fb41dec6-e9e0-4b32-a934-440e5af9bb07.png)

MMD Tools refers to **Japanese MMD name (name_j)** column when loading motion.
So fill in the column with the preferred bone names.
![image](https://user-images.githubusercontent.com/70152495/178097624-4404867f-c759-46ab-bb44-75e71a101731.png)
