### ISSUE TITLE
unable to install addon into blender

### ISSUE THREAD

**Issue by PlutoMarionette** [UuuNyaa/blender_mmd_tools#56]
mmd tool version: 2.2.6

![Screenshot (38)](https://user-images.githubusercontent.com/94062994/179396639-44d04eff-6ef7-446e-b944-c6af2d7a44dc.jpg)
 
does anyone know what to do?

**Comment by listelin** [comment]
Unfortunately, blender 2.70 is not supported.
https://mmd-blender.fandom.com/wiki/MMD_Tools#Installation
