### ISSUE TITLE
morphs not getting imported from .vmd

### ISSUE THREAD

**Issue by bwalker22** [UuuNyaa/blender_mmd_tools#57]
Is there a way to import a .vmd file with shape key animations to a mesh that is translated? I only found a way to import shape key animations with the original name

**Comment by UuuNyaa** [comment]
Unfortunately, it is not possible to import facial motions into the morph names after translation.

However, you can batch convert morph names using the Global Translation feature.
![image](https://user-images.githubusercontent.com/70152495/179818616-e9b76f10-168a-4ef9-be70-71b6b9de4bb5.png)

**Comment by bwalker22** [comment]
is it possible to translate the blender name column to japanese?
I read in another issue about translating english to japanese but it's not what im looking for

![Capture](https://user-images.githubusercontent.com/61926475/179824016-bf014fa9-301e-4cc7-bb53-2cba3eb14492.JPG)

**Comment by UuuNyaa** [comment]
Try the following steps
1. Select `Translate to Japanese` preset
2. Select `Japanese MMD Name (name_j)` column
3. Press `Execute` button

**Comment by bwalker22** [comment]
I dont have a preset to Translate to japanese. I just re installed to see if it would show the preset but i still dont see it

![Capture](https://user-images.githubusercontent.com/61926475/180432072-49fa1027-3779-43cf-91c9-1014d45ea3a2.JPG)

**Comment by UuuNyaa** [comment]
Sorry 😥
There is no preset dictionary for English to Japanese translation.
You can choose translate them one by one by hand or prepare your own English to Japanese dictionary.

**Comment by UuuNyaa** [comment]
I may add a general translation dictionary in the future.
However I would prefer to have a user defined dictionary for each model.
