### ISSUE TITLE
VMD isn't shown as MMD

### ISSUE THREAD

**Issue by mtsmfm** [UuuNyaa/blender_mmd_tools#59]
Hello, thank you for maintaining awesome addon.
In most cases importing VMD works well, amazing!

I found a weird case and I'd like to share this behavior.

As you can see, right knee is misaligned.

![image](https://user-images.githubusercontent.com/1796864/180643677-4aa5fb77-298a-48bc-b317-a15959371db2.png)

![image](https://user-images.githubusercontent.com/1796864/180643673-e9eef914-84aa-49bd-8f8d-06cd6fb7f231.png)

You can reproduce this by using alicia and this motion:

- https://3d.nicovideo.jp/alicia/
- [motion.zip](https://github.com/UuuNyaa/blender_mmd_tools/files/9175618/motion.zip)

The motion just initializes center, right leg IK and right leg.

**Comment by UuuNyaa** [comment]
This happens often, because the IK in MMD and Blender work somewhat differently.
So, please rotate `足.R` bone to adjust it.

**Comment by mtsmfm** [comment]
@UuuNyaa I see. Thank you for your reply!

JFYI, I've tried some VMD converters (they're not for Blender plugin, actually Unity plugin though).
I've found [MMD4Mecanim](https://stereoarts.jp/) outputs excellent result despite UnityVMDPlayer similar with blender_mmd_tools.

[MMD4Mecanim](https://stereoarts.jp/):

![image](https://user-images.githubusercontent.com/1796864/182832655-11ed92f1-0177-4691-b6ba-4d4626e069f6.png)

[UnityVMDPlayer](https://github.com/hobosore/UnityVMDPlayer) (For some reason Alicia isn't recognized well):
![image](https://user-images.githubusercontent.com/1796864/182835804-b58d4089-5395-4995-9b6a-775045286e45.png)

It's closed source however I think MMD4Mecanim has some hacks to convert VMD into FBX to be more closely to MMD and we may have a room for improvement.

**Comment by UuuNyaa** [comment]
Thanks for the information 😃
I found a workaround. However, I am not sure if this works for all models.

https://user-images.githubusercontent.com/70152495/182842717-0db00b39-9941-4b77-8377-00f657cba185.mp4
