### ISSUE TITLE
Unable to install plugin in Blender 2.93 or 3.2

### ISSUE THREAD

**Issue by PlatypussDivva** [UuuNyaa/blender_mmd_tools#61]
Hello, when trying to install plugin on blender 2.93 or 3.2 I get the following error:
![mmd_tools_error](https://user-images.githubusercontent.com/158325/185722795-78076b06-4600-47f7-8388-19a064d8d894.jpg)

**Comment by UuuNyaa** [comment]
Please try a clean install with all add-ons removed/disabled.
