### ISSUE TITLE
Allow for morph drivers to have a keyframe property

### ISSUE THREAD

**Issue by ChandelureF-5** [UuuNyaa/blender_mmd_tools#79]
This would make it easier to do dynamic animation by allowing people to key both material and shape morphs.

**Comment by UuuNyaa** [comment]
Why not add a keyframe to`.placeholder` ?
https://mmd-blender.fandom.com/wiki/MMD_Tools/Manual#Morph_(Material,_UV,_Bone_and_Group_Morphs)

**Comment by ChandelureF-5** [comment]
Why can't we give `.placeholder` an auto-keyframe setup yet?

**Comment by UuuNyaa** [comment]
The following URL might be helpful:
https://www.reddit.com/r/blenderhelp/comments/4eqjvs/automatic_keyframing_of_shape_keys/

Please let me know in detail what you want to do.
