### ISSUE TITLE
It just won't let me use it

### ISSUE THREAD

**Issue by HyperSsonic** [UuuNyaa/blender_mmd_tools#81]
![image](https://user-images.githubusercontent.com/120762413/208215931-8eead90b-d86c-436d-bed4-83ad11f035c9.png)
I try and click the check box, but this just keeps appearing and I don't know what to do.

**Comment by lordscales91** [comment]
It's working fine for me, and I'm using the same Blender version as you. Have you installed the latest release from https://github.com/UuuNyaa/blender_mmd_tools/releases ?

**Comment by HyperSsonic** [comment]
Apparently I wasn't cause I eventually got it to work, still, thanks for this addon, lad.

**Comment by Blue-EyesWhiteDragon** [comment]
I get the same traceback as mentioned here. With the latest release.
