### ISSUE TITLE
how to disable the foot IK?

### ISSUE THREAD

**Issue by lucasjinreal** [UuuNyaa/blender_mmd_tools#84]
![image](https://user-images.githubusercontent.com/21303438/212472307-db5a4383-cee3-44c2-94cc-775bc93de59c.png)

**Comment by UuuNyaa** [comment]
Please try the **IK Toggle** buttons.
![image](https://user-images.githubusercontent.com/70152495/216130070-a3f4bc28-2cfd-4bb8-9554-3116d33c5a8f.png)
