### ISSUE TITLE
how to apply rigid body via python script?

### ISSUE THREAD

**Issue by wikid24** [UuuNyaa/blender_mmd_tools#87]
Hi,

I am trying to automate the creation of rigid bodies using python code. My model does not have any rigid bodies yet, but I want to create them automatically.

I created a CSV file that lists every rigid body needed, and it has all the parameters.

I want to create a function that will create a rigid body based on the parameters in the CSV and creates the rigid body for me. 

the CSV parameters are:
```
name_j = '$name_j'
name_e = '$name_e'
collision_group_number = 0
collision_group_mask = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] 
rigid_type = 0 #0= Bone, 1 = Physics, 2 = Physics+Bone
rigid_shape = 'SPHERE' #SPHERE, BOX, CAPSULE
size = [0.6, 0.6, 0.6]  #size[0] = X, size[1] = Y, size[2] = Z
mass = 1 
friction = 0.5
bounce = 0 #restitution
linear_damping = 0.04
angular_damping = 0.1
```

![image](https://user-images.githubusercontent.com/19479648/215190667-09de318d-166c-4740-8d05-6162ae450a79.png)

How do I write the code to pull the **mmd_core.operators.rigid_body** library properly to add a rigid body? it already has the  **AddRigidBody** class and **__add_rigid_body** function, but I do not know how to call them properly. Any help would be appreciated!

**Comment by wikid24** [comment]
nevermind, I found out how to do it.

```

import bpy
from mmd_tools.operators.rigid_body import AddRigidBody

"""
name_j = '$name_j'
name_e = '$name_e'
collision_group_number = 0
collision_group_mask = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] 
rigid_type = 0 #0= Bone, 1 = Physics, 2 = Physics+Bone
rigid_shape = 'SPHERE' #SPHERE, BOX, CAPSULE
size = [0.6, 0.6, 0.6]  #size[0] = X, size[1] = Y, size[2] = Z
mass = 1 
friction = 0.5
bounce = 0 #restitution
linear_damping = 0.04
angular_damping = 0.1
"""
bpy.ops.mmd_tools.rigid_body_add(
    name_j='$name_j'
    ,name_e='$name_e'
    ,collision_group_number=0
    ,collision_group_mask=[False] * 16
    ,rigid_type='1'
    ,rigid_shape='SPHERE'
    ,size=(1.0, 1.0, 1.0)
    ,mass=2.0
    ,friction=0.5
    ,bounce=0.5
    ,linear_damping=0.04
    ,angular_damping=0.1
)

```

**Comment by UuuNyaa** [comment]
Good job!

My gist might have been helpful...
https://gist.github.com/UuuNyaa/925be8e892f3793386ff3db4e9e5cf7e

**Comment by wikid24** [comment]
wow that's awesome, and seems really useful! 

Can the code you just sent be used to split an existing simple skirt into a well-defined one with rigid bodies & joints applied? Or was the fractured mesh already split before the code was applied?

Let's say I want to replace the existing a skirt with a more complex one:

![image](https://user-images.githubusercontent.com/19479648/216215157-6c065864-622f-45b8-ad01-2bf005e67df4.png)

1) create a new skirt bones, with more than the existing one (subdivide isn't good enough, need to create more bone parents)

2) transfer the weight painting, and vertex groups to new skirt bones.

3) create rigid bodies for the new bones vertically user specifying min/max parameters
    Using mass as an example, If I want the skirt to be heaviest at bottom and lightest on top. If user specifies mass min value =1 and max value=10, and there are 5 bones to be replaced, top to bottom mass values should be [1 , 3.25 , 5.5 , 7.75 ,10 ] 

4) create the joints for the vertical chain of rigid bodies (specifying the min/max values similar to above.)

5) create horizontal joints for the rigid bodies with the least amount of effort req'd

If write this on my own, it will take weeks/months to figure it out, so hopefully you might have some ideas?

**Comment by UuuNyaa** [comment]
> Can the code you just sent be used to split an existing simple skirt into a well-defined one with rigid bodies & joints applied?

It would probably not be applicable.
But [`create_rigid_bodies`](https://gist.github.com/UuuNyaa/925be8e892f3793386ff3db4e9e5cf7e#file-mmd_rigidbody_setup_test-py-L222) function is a good reference for batch generation of rigid bodies.

> Or was the fractured mesh already split before the code was applied?

Yes. My gist is for a mesh that has already been split for destruction effect.

> Let's say I want to replace the existing a skirt with a more complex one:

I think 1 (create bones) and 2 (weight paint) are very difficult.
Why not bone subdividing?
What kind of bone structure do you need?

I recommend the following video's solution:
https://youtu.be/pRJNJDFSYfk

**Comment by wikid24** [comment]
Thanks uuuNyaa, I watched the tutorial, 'rigid body to cloth' is good if you are staying in blender, but I am trying to convert to MMD so I need to use methods that MMD knows how to interpret (rigid bodies and joints). the reason for a more complex bone structure for skirt is because the rigid bodies that looks like this, it does not look good for physics:

![image](https://user-images.githubusercontent.com/19479648/216414865-defc9a8d-4dec-497a-bee7-e305d695351e.png)

since subdivide only splits bones on a bone chain, it will not create a new bone between front_L and side_L like so, so that rigid bodies will look better in MMD:
![image](https://user-images.githubusercontent.com/19479648/216416479-c52fe724-d1c8-4d14-b8c2-2b46b500a77c.png)

the reason for creating new skirt bones is so that rigid bodies when exporting to MMD the physics will look much better.

**Comment by wikid24** [comment]
ideally I would like to write the code to generate a skirt similar to a genshin MMD  model where it can be more complex like this example (Lisa genshin model on the right):

![image](https://user-images.githubusercontent.com/19479648/216422038-f0e66f82-1930-4fe3-b4f9-baa3d182eec0.png)

**Comment by UuuNyaa** [comment]
I think you are taking on a very big challenge.
Once you have solved automatic bone structure creation, the following weight painting code may help you.
https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/blob/main/mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py#L359

**Comment by wikid24** [comment]
I think I may have found a workaround solution instead of writing code for automatic bone creation-- There's an MMD model that already _mostly_ matches the proportions of anything I'll import, namely an (FFXIV) model. It has a a complex skirt structure, is already weight painted, and has rigid bodies and joints: https://www.deviantart.com/leveiileurs/art/MMD-Model-DL-FFXIV-Y-shtola-Rhul-866143353

I'm thinking if I can in my blender project:
1)  import the skirt bones, skirt mesh, rigid bodies and joints as it's own object
2)  scale the object to meet the proportions of my model
3)  transfer the bones, rigid bodies and joints to my model
4) do a weight paint transfer

it might work, but what I don't know is if MMD Tools will accept rigid bodies and joints from one armature transferred to another armature without breaking.

If this can work, I can create code to automatically import these objects, scale it to the target armature, and transfer to the target armature with less effort. Thoughts?

**Comment by UuuNyaa** [comment]
There is already a feature to port parts between two MMD models.
You may find this feature useful.
https://youtu.be/wtoTxMfC77g

**Comment by wikid24** [comment]
Thanks! I will find a way to use that functionality.

I decided to go for the approach of dynamically generating a new skirt mesh & bones and automatically weight paint, 
Then transfer the new skirt bones to the existing model and do a weight paint transfer. 


https://user-images.githubusercontent.com/19479648/216857492-5510ac87-89e8-48bd-b804-d7cf40e2c25c.mp4


I will leverage the AddRigidBones class and AddJoints classes create new rigid bodies and joints for the new skirt bones. :)
