### ISSUE TITLE
Physics Build generates bonetracks and temporary ncc under selected collections

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_tools#9]
以下の手順により、mmd_bonetrackと、nccファイルが意図しないコレクション配下に作成されます
(1) (mmdモデルを含まない)別のコレクションを選択
(2) mmdモデルのトップレベルemptyを選択
(3)物理構築ボタンを押す
![スクリーンショット 2021-12-05 234115](https://user-images.githubusercontent.com/44924233/144751265-f8caa449-50ad-41ca-82b9-b63d525dbd2b.jpg)

一旦mmd_bonetrackと、temporary/nccを削除して、再度構築すれば問題ありませんが、
他のコレクション配下にこれらのファイルを意図的に作成することはまず無いと思います

直近選択したコレクションによらず、通常通りmmd_bonetrackはrigidbodies配下に、nccはtemporary配下に作成するようにできないでしょうか？

優先度が高いわけではありませんが可能なら確認お願いします

---
The following procedure will create an mmd_bonetrack and ncc file under an unintended collection.

(1) Select a different collection (that does not contain mmd models)
(2) Select the top-level empty of the mmd model
(3) Press the physics build button

If I delete mmd_bonetrack and temporary/ncc (or clean physics) and rebuild them again, it should be fine.
But it is unlikely that someone would create these files under another collection.

Is it possible to create mmd_bonetrack under rigidbodies and ncc under temporary as usual, regardless of the most recently selected collection?

It's not a high priority, but if it's possible, please check.

**Comment by UuuNyaa** [comment]
提案ありがとうございます。
物理構築操作でも同じ問題が発生しますね。
モデルが属するコレクションにオブジェクトを作成するように修正します。

Thanks for the suggestion.
The same problem occurs in physics build operation.
I will fix it to create objects in the collection to which the model belongs.
