### ISSUE TITLE
bones in envelope view are too big

### ISSUE THREAD

**Issue by macfifa** [UuuNyaa/blender_mmd_tools#93]
i m trying to write a script that take the size of the bone and use it after i test it on mmd model imported by your addon
the bone size are very big. you can see it in envelope view and edit it also in envelope mode(strange) so i fix the size by alt S
but can you see why it is imported that big?
![1](https://user-images.githubusercontent.com/16125957/232291916-3188c633-9a81-4399-9a3c-c3ea61a2e307.png)
![2](https://user-images.githubusercontent.com/16125957/232291950-e3e616cb-2189-455f-9ab9-31eeb29d296e.png)

**Comment by nagadomi** [comment]
Envelope is a mesh deformation method, not just a bone display mode.
mmd_tools does not use Envelope, instead it uses Vertex Weight.
So mmd_tools does not change its unused values, I guess.
It means that you should not use the Envelope display mode.
